ErrorLogging when HereApiKey not found
amosproj/amos2021ws01-geo-data-search pull request #136
Opened 2021-12-04 14:02 UTC by chrisjherm

2021-12-05 22:13 UTC, Decappi commented
I love it that the container starts now, when the file isn't there. Let's clean this up though.
Readme entry is still missing - let's add a line to that too.

2021-12-05 22:19 UTC, Decappi requested changes
Readme needs to be updated

2021-12-06 22:39 UTC, Decappi commented on src/backend/src/main/java/com/example/backend/helpers/HereApiKey.java
> +    private static final String SEP = File.separator;
I'm confused by this - does the container under windows use different separators?

2021-12-06 22:39 UTC, Decappi approved these changes

2021-12-07 10:26 UTC, chrisjherm commented on src/backend/src/main/java/com/example/backend/helpers/HereApiKey.java
> +    private static final String SEP = File.separator;
Windows uses different separators but I don't know how this works in the container. So I just added a solution just in case

2021-12-07 10:29 UTC, merged